name: "reinfolib"
version: "1.0.0"

profile: "reinfolib"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "shared/macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  reinfolib:
    +database: reinfolib
    main:
      raw:
        +materialized: table
      stg:
        +materialized: view
      mart:
        +materialized: table
    urban_planning:
      raw:
        +materialized: table
      stg:
        +materialized: view
      mart:
        +materialized: table
